app.py
from flask import Flask
from config import Configuration
from posts.blueprint import posts

app = Flask(__name__)
app.config.from_object(Configuration)

app.register_blueprint(posts, url_prefix='/realties')

main.py
from app import app
import view


if __name__ == '__main__':
    app.run(debug=True)

posts/blueprint.py
from flask import Blueprint
from flask import render_template


posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/')
def index():
    return render_template('posts/index.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
		{% block title %}

		{% endblock %} | Flask proj
	</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="{{ url_for('index')}}">Tagproj</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{url_for('posts.index')}}">Недвижимость</a>
				</li>
				<li class="nav-item">
					<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
				</li>
			</ul>
			<form class="form-inline my-2 my-lg-0">
				<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
			</form>
		</div>
	</nav>
	<div class="container">
		<div class="row">
			<h1>
				{% block content_title %}

				{% endblock %}
			</h1>
			{% block content %}

			{% endblock %}
		</div>
	</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block title %}
	Недвижимость
{% endblock %}


{% block content_title %}
	Актуальная недвижимость
{% endblock %}


{% block content %}
	...
{% endblock %}